### ISSUE TITLE
Test failures on master

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#226]
Master build fails on the following tests:

```
com.reprezen.swagedit.model (3)
  ModelTest.parseRootValues     

First failure:          #88     Changes (7)     17 Oct 16 16:09
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.reprezen.swagedit.model.ModelTest.parseRootValues(ModelTest.java:53)
« Hide stacktrace
  ModelTest.testParseArrayValues    

First failure:          #88     Changes (7)     17 Oct 16 16:09
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.reprezen.swagedit.model.ModelTest.testParseArrayValues(ModelTest.java:141)
« Hide stacktrace
  ModelTest.testParseEnumArrayValues    

First failure:          #88     Changes (7)     17 Oct 16 16:09
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.reprezen.swagedit.model.ModelTest.testParseEnumArrayValues(ModelTest.java:99)
```

@ghillairet , can you please have a look?

**Comment by ghillairet** [comment]
Fixed in https://github.com/RepreZen/SwagEdit/commit/2ead105d16f0b88f51c816b584d99a6d751246b2
