### ISSUE TITLE
Confusing validation message on bad indentation

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#350]
Create this v3 spec:
```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT

paths: {}                
                
components:

  schemas:
    Pet:
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
       name:
          type: string
```
Try to understand what's wrong with it based on the validation message:
<img width="480" alt="screen shot 2017-06-05 at 11 19 17 am" src="https://cloud.githubusercontent.com/assets/644582/26790232/015174b6-49e1-11e7-928c-de5189eac251.png">

## Answer
Pet#name should be indented one space to the right.

I've seen this validation message many times, and every time it's very hard to find the real problem.

**Comment by ghillairet** [comment]
You suggest that we should change the error message?

**Comment by tfesenko** [comment]
The issue is fixed, but I think the fix has a side effect. Element name editing creates multiple (really a lot of) errors in the error log:
![errors](https://user-images.githubusercontent.com/644582/26993706-5f310b88-4d32-11e7-81db-1a82a3d692fd.gif)

Exception:
```java
com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while scanning a simple key
 in 'reader', line 37, column 7:
          SO
          ^
could not find expected ':'
 in 'reader', line 39, column 5:
        MapObject:
        ^

 at [Source: java.io.StringReader@768b79db; line: 34, column: 21]
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:27)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:343)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserializeObjectNode(NodeDeserializer.java:58)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserialize(NodeDeserializer.java:40)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserializeObjectNode(NodeDeserializer.java:65)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserialize(NodeDeserializer.java:40)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserializeObjectNode(NodeDeserializer.java:65)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserialize(NodeDeserializer.java:40)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserializeObjectNode(NodeDeserializer.java:65)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserialize(NodeDeserializer.java:40)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserializeObjectNode(NodeDeserializer.java:65)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserialize(NodeDeserializer.java:40)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserializeObjectNode(NodeDeserializer.java:65)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserialize(NodeDeserializer.java:40)
	at com.reprezen.swagedit.core.model.NodeDeserializer.deserialize(NodeDeserializer.java:1)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1623)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1217)
	at com.reprezen.swagedit.core.model.Model.parseYaml(Model.java:86)
	at com.reprezen.swagedit.core.editor.JsonDocument.parseModel(JsonDocument.java:166)
	at com.reprezen.swagedit.core.editor.JsonDocument.onChange(JsonDocument.java:131)
	at com.reprezen.swagedit.core.editor.JsonEditor$1$1.run(JsonEditor.java:114)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: while scanning a simple key
 in 'reader', line 37, column 7:
          SO
          ^
could not find expected ':'
 in 'reader', line 39, column 5:
        MapObject:
        ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:340)
	... 45 more

```

**Comment by ghillairet** [comment]
I fixed the logging issue in https://github.com/RepreZen/KaiZen-OpenAPI-Editor/commit/941009faead73be5005be52ef658510f0ee448be - I pushed it in master directly.

**Comment by tfesenko** [comment]
941009f fixed the side-effect. Closing
