### ISSUE TITLE
Failure running with java 11

### ISSUE THREAD

**Issue by cvgaviao** [RepreZen/KaiZen-OpenAPI-Editor#495]
I just installed Kaizen in a new macOS machine that is using java11.0.2.

Strangely, only the swagger v2 was working, even in preferences.

Then I found these errors on ErrorLog view: 
```
org.osgi.framework.BundleException: Could not resolve module: com.reprezen.swagedit.openapi3 [483]
  Unresolved requirement: Require-Bundle: com.github.eclipsecolortheme; resolution:="optional"
  Unresolved requirement: Require-Bundle: com.reprezen.kaizen.openapi-parser; bundle-version="3.0.1"
    -> Bundle-SymbolicName: com.reprezen.kaizen.openapi-parser; bundle-version="4.0.1.201809111905"
       com.reprezen.kaizen.openapi-parser [480]
         Unresolved requirement: Import-Package: com.reprezen.jsonoverlay.gen; resolution:="optional"
         Unresolved requirement: Import-Package: javax.mail.internet
           -> Export-Package: javax.mail.internet; bundle-symbolic-name="com.sun.mail.javax.mail"; bundle-version="1.6.1"; version="1.6.0"; uses:="javax.activation,javax.mail"
              com.sun.mail.javax.mail [484]
                Unresolved requirement: Import-Package: javax.activation

	at org.eclipse.osgi.container.Module.start(Module.java:452)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1784)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1763)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1726)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1657)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

```

```
java.lang.NullPointerException
	at com.reprezen.swagedit.core.editor.ValidationOperation.run(ValidationOperation.java:60)
	at com.reprezen.swagedit.editor.SwaggerEditor.lambda$0(SwaggerEditor.java:45)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore.firePropertyChangeEvent(ChainedPreferenceStore.java:156)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore.handlePropertyChangeEvent(ChainedPreferenceStore.java:368)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore.access$0(ChainedPreferenceStore.java:345)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore$PropertyChangeListener.propertyChange(ChainedPreferenceStore.java:70)
	at org.eclipse.ui.preferences.ScopedPreferenceStore$2.run(ScopedPreferenceStore.java:348)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.firePropertyChangeEvent(ScopedPreferenceStore.java:345)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.lambda$0(ScopedPreferenceStore.java:182)
	at org.eclipse.core.internal.preferences.EclipsePreferences$2.run(EclipsePreferences.java:848)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.preferences.EclipsePreferences.firePreferenceEvent(EclipsePreferences.java:851)
	at org.eclipse.core.internal.preferences.EclipsePreferences.remove(EclipsePreferences.java:958)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$StylingPreferencesHandler.resetOverriddenPreferences(PartRenderingEngine.java:1473)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$StylingPreferencesHandler.resetOverriddenPreferences(PartRenderingEngine.java:1467)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$StylingPreferencesHandler.lambda$0(PartRenderingEngine.java:1456)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4363)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4352)
	at org.eclipse.swt.widgets.Display.release(Display.java:3821)
	at org.eclipse.swt.graphics.Device.dispose(Device.java:192)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:171)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
```

**Comment by cvgaviao** [comment]
Seems that the installer download page was outdated. After updating the eclipse installer and reinstalling the eclipse for java the problem gone.

**Comment by tedepstein** [comment]
@cvgaviao , glad you got it working.

> Seems that the installer download page was outdated. After updating the eclipse installer and reinstalling the eclipse for java the problem gone.

Which download page was outdated? Something related to KaiZen Editor, specifically, or an Eclipse IDE download page?
